version: '3.9'

services:
    new_app:
      build: ./
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - articles
    articles:
      image: 'postgres:latest'
      restart: always
      ports:
        - 5432:5432
      env_file:
        - .env  
      volumes:
        - ./db-data/:/var/lib/postgresql/data/
volumes:
  db:
    driver: local

